# Project information
site_name: How we teach ourselves
site_description: 'How we teach ourselves"
site_author: 'Maximilian Ho'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/maximilian-ho/how-we-teach-ourselves'

# Documentation and theme
theme: 'readthedocs'

# Options
extra:
  author:
    github: 'maximilian-ho'

# Extensions
markdown_extensions:
  - admonition

pages:
    - Home: index.md
    - Learning how to be bored: learning_how_to_be_bored.md
    - Reading epub books using Moon+ Reader: reading_epub_books_using_moon_plus_reader.md
    - Annotating pdf textbooks using Foxit PDF Editor: annotating_pdf_textbooks_using_foxit_pdf_editor.md 
