site_name: How we teach ourselves

nav:
   - Homepage: "index.md"
   - Learning how to be bored: "boredom.md"
   - Reading epub ebooks using Moon+ Reader: "epubs.md"
   - Annotating pdf textbooks using Foxit PDF editor: "pdfs.md"

repo_url: https://github.com/maximilian-ho/how-we-teach-ourselves

theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.png
  features:
    - toc.integrate
  palette:
    primary: indigo
  icon: 
    repo: fontawesome/brands/github

plugins: []

extra_css:
  - stylesheets/extra.css
