# Project information
site_name: How we teach ourselves

# Documentation and theme
theme: 'readthedocs'

# Extensions
markdown_extensions:
  - admonition

nav:
    - Home: index.md
    - Developing our boredom muscles: boredom.md
    - Reading epub books using Moon+ Reader: epubs.md
    - Annotating pdf textbooks using Foxit PDF Editor: pdfs.md 
