site_name: How we teach ourselves

nav:
   - Homepage: "index.md"  
   - Reading epub ebooks using Moon+ Reader: "epubs.md"
   - Annotating pdf textbooks using Foxit PDF editor: "pdfs.md" 

theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.png
  features:
    - toc.integrate
  palette:
    primary: indigo 

plugins: []

extra_css:
  - stylesheets/extra.css
